### ISSUE TITLE
Database output in xlsx

### ISSUE THREAD

**Issue by felipeZ** [SCM-NV/qmflows#116] opened 2018-12-05 10:54 UTC
The [quantum dot](https://github.com/SCM-NV/qmflows/blob/master/src/qmflows/qd.py) functionality produces output in `xlsx` format that is not suitable for most users. @BvB93 Could you please change the output of the database to something more general like: `csv`, `json`, etc.

**Comment by BvB93** [comment] 2018-12-06 15:37
Output changed from .xlsx to .json format. 
As of the moment a duplicate of the output is still exported to an .xlsx file, however this this file longer used for reading results from previous calculations (i simply like my spreadsheets for data analyses). 
xlsx exporting will probably be either removed or changed into an optional argument at some point in the future.

**Closed by BvB93** 2018-12-06 15:37 UTC
